# Generated by Django 5.1.3 on 2025-12-02 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_producto_embedding_producto_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la orden', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Estado actual de la orden', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del PaymentIntent de Stripe', max_length=255, null=True)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_phone', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_country', models.CharField(default='US', max_length=2)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la orden', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de productos ordenados')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la compra', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item (precio_unitario * cantidad)', max_digits=10)),
                ('order', models.ForeignKey(help_text='Orden a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('producto', models.ForeignKey(help_text='Producto ordenado', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
